### ISSUE TITLE
TODO: Create a 64 bit app that uses the converted model databse and loads it using the DAS code in PKSim

### ISSUE THREAD

**Issue by msevestre** [msevestre/OSPSuite-64bit#4]
The idea here is to make sure that the concept we are using in PKSim will work

- [x] Create a 64bit App
- [x] Copy the DAS code (Data Access Layer)
- [x] Copy the code from `DataTableToMetaDataMapper`
- [x] Connect with the Model database that you have converted
- [x] Executing names queries (e.g. "VIEW_xxx")
- [x] Run a query directly against the database

If that all work, we are probably good to go
