### ISSUE TITLE
TODO: Test compatibility of MikTex Engine with 64bit

### ISSUE THREAD

**Issue by msevestre** [msevestre/OSPSuite-64bit#5]
- [x] Create a 64 bit app
- [x] Instantiate the reporting engine (for example by creating a dummy report, see InstallationValidation to get it going)
- [x] Install all of that on a 64bit machine (e..g Install the miktex,msi and copy the bin folder and run it)

If we can create a pdf file, we are good to go
